name: delete branch on closed
on:
  pull_request:
    types: [closed]
permissions: read-all|write-all

jobs:
  delete-branch:
    runs-on: ubuntu-latest
    steps:
      - name: delete branch
        # 1.4.3
        uses: SvanBoxel/delete-merged-branch@2b5b058e3db41a3328fd9a6a58fd4c2545a14353
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
